### ISSUE TITLE
$TypeName not working for user-defined classes

### ISSUE THREAD

**Issue by ethanCrobison** [ianhorswill/BotL#2]
`X=$String, writenl(X)` runs fine
`X=$BotlManager, writenl` throws exception (on .botl file load):
<img width="384" alt="captura de pantalla 2017-02-20 a la s 20 46 01" src="https://cloud.githubusercontent.com/assets/7151453/23148852/a24e3b82-f7ad-11e6-901b-c6a6be721ba6.png">

Adding namespace (i.e., `X=$Game.AI.Botlmanager`) results in a similar error.

**Comment by ianhorswill** [comment]
Someplace in your C# code, add the following:

              BotL.TypeUtils.AddTypeSearchPath("Game");
              BotL.TypeUtils.AddTypeSearchPath("Game.AI");

-ian

**Comment by ianhorswill** [comment]
Also, you should be able to do $"Game.AI.Tpe" and have it work.  But if you don't have the quotes, it parses as an application of the . operator and gets confused.

-ian

Sent from mobile device; apologies for terseness and/or typos

On Feb 20, 2017, at 8:48 PM, Ethan Robison <notifications@github.com<mailto:notifications@github.com>> wrote:


X=$String, writenl(X) runs fine
X=$BotlManager, writenl throws exception (on .botl file load):
[captura de pantalla 2017-02-20 a la s 20 46 01]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_7151453_23148852_a24e3b82-2Df7ad-2D11e6-2D901b-2Dc6a6be721ba6.png&d=CwMCaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=8iJxN6CcyFWMGReNU_eUqmL0MvJBBwh1DEi4zrWiCRM&m=gejxpmTv1j7xKPYXaILBkKRgcEATpXbN1yr6TNdIzgg&s=upHjCgs-JsowQHzQaJxuuVCuabxfHTbVUiHG-MPIWE4&e=>

Adding namespace (i.e., X=$Game.AI.Botlmanager) results in a similar error.

-
